In [1]:
import requests
import json
from pprint import pprint
import numpy as np
import pandas as pd
import os
import csv
import datetime as dt

from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy import Column
from sqlalchemy import Integer, String, Float

import sqlalchemy
from sqlalchemy import create_engine, func, inspect
from sqlalchemy_utils import database_exists, create_database
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Numeric, Text, Float, Date

from math import radians, sin, cos, asin, sqrt # used to calculate distance of room and city longs and lats

from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

import multiprocessing as mp

# Google API Key
# from config import gkey
from flask import Flask, jsonify

In [2]:
countryList = ["United States"]

In [3]:
# results = requests.get(f'https://public.opendatasoft.com/api/records/1.0/download/?dataset=air-bnb-listings&facet=city&facet={x}&facet=geolocation&facet=id&facet=geolocation&facet=name&facet=price&facet=room_type&format=json').json()
def api_call(x):
    results = requests.get(f'https://data.opendatasoft.com/api/records/1.0/download/?dataset=airbnb-listings%40public&facet=city&facet=country&facet=geolocation&facet=id&facet=geolocation&facet=name&facet=price&facet=room_type&refine.country={x}&format=json').json()
    results = [r["fields"] for r in results]
    return results

In [4]:
def main():
  pool = mp.Pool(9)
  result = pool.map(api_call, countryList)
  return result

if __name__ == "__main__":
    result = main()

In [6]:
pprint(result[0][0])

{'access': "We're in the heart of the Mission. Located on a small, quiet "
           'street between Valencia and Mission Streets, we are surrounded by '
           'all the awesome bars, restaurants and shopping of the Mission. '
           'Craft beer bars The Best Tacos and Burritos Dolores Park '
           'Michelin-starred restaurants Tartine Bakery Hipster fashion '
           'Artisinal chocolate factories GREAT coffee  Incredible murals  '
           'Sunshine (The Mission gets more sun that the rest of San '
           'Francisco) These are just some of the things available within a '
           'one minute walk from our pad. As foodies we have a list of amazing '
           "bars and restaurants you should check out while you're here. And "
           "don't hesitate to ask if there's something in particular you're "
           'looking for. Getting Around The BART (aka subway, train, tube, '
           "etc.) is located at 16th and Mission. That's two blocks from the "
           'apartment and it will take you anywhere and everywhere in the city '
           'and in the Bay Area - most importantly it will take you to Super '
           'Bowl City in 6 minutes - yes I timed it.  You can als',
 'accommodates': 2,
 'amenities': 'TV,Wireless Internet,Kitchen,Buzzer/wireless '
              'intercom,Essentials,24-hour check-in',
 'availability_30': 0,
 'availability_365': 0,
 'availability_60': 0,
 'availability_90': 0,
 'bathrooms': 0.0,
 'bed_type': 'Real Bed',
 'bedrooms': 1,
 'beds': 1,
 'calculated_host_listings_count': 2,
 'calendar_last_scraped': '2017-04-02',
 'calendar_updated': '13 months ago',
 'cancellation_policy': 'flexible',
 'city': 'San Francisco',
 'cleaning_fee': 60,
 'country': 'United States',
 'country_code': 'US',
 'description': 'Single bedroom in awesomely-located Mission 2br apartment for '
                'weekend adventures. Just feet from the best restaurants, bars '
                'and shopping of Valencia Street and the Mission District and '
                'just two blocks from the BART train. The two-bedroom, '
                'one-bathroom has fast wifi, a large living room (with a TV '
                'with HBO and HBO-on-Demand with every season of every show!). '
                'Our kitchen has a 4-top stove and oven. Large refrigerator '
                'and freezer and full suite of cooking and eating utensils. '
                'The bathroom has a shower with hot water, great water '
                'pressure and soap, shampoo and conditioner + fluffy clean '
                'towels. The bedroom is spacious with a desk, dresser and '
                'mirror. I have a roommate who lives in the other bedroom who '
                "can give you the key. Aside from that we'll stay out of your "
                "hair! We're in the heart of the Mission. Located on a small, "
                'quiet street between Valencia and Mission Streets, we are '
                'surrounded by all the awesome bars, restaurants and shopping '
                'of the Mission. Some of my favorite things about th',
 'experiences_offered': 'none',
 'extra_people': 0,
 'features': 'Host Has Profile Pic,Host Identity Verified,Is Location '
             'Exact,Instant Bookable',
 'first_review': '2016-02-14',
 'geolocation': [37.76221382842841, -122.42032216865074],
 'guests_included': 1,
 'host_about': "I'm a voracious foodie born and raised in New York City. I've "
               'lived all over the world -- China, Israel, Scotland -- but '
               'live in San Francisco now!\r\n'
               '\r\n'
               'A little about me:\r\n'
               "1. I'm a cyclist and commute everywhere by bike\r\n"
               '2. Currently working on opening a restaurant in NYC\r\n'
               '3. Love doing anything outdoors - picnic, hiking, frisbee, '
               "reading -- the upshot for you is that I won't spend much time "
               'besides from sleeping in your apartment!\r\n'
               "4. Fun fact: I'm learning how to sail! Once I actually know "
               "what I'm doing I'd love to take you for a sail.",
 'host_id': '25149739',
 'host_listings_count': 2,
 'host_location': 'San Francisco, California, United States',
 'host_name': 'Sam',
 'host_neighbourhood': 'Mission District',
 'host_picture_url': 'https://a0.muscache.com/im/users/25149739/profile_pic/1435269900/original.jpg?aki_policy=profile_x_medium',
 'host_since': '2014-12-23',
 'host_thumbnail_url': 'https://a0.muscache.com/im/users/25149739/profile_pic/1435269900/original.jpg?aki_policy=profile_small',
 'host_total_listings_count': 2,
 'host_url': 'https://www.airbnb.com/users/show/25149739',
 'host_verifications': 'email,phone,reviews,jumio',
 'house_rules': 'Take your shoes off in the hall. No shoes in the bedrooms.  '
                'Treat the house as you would your own.',
 'id': '11067041',
 'interaction': 'I have a roommate who lives in the other bedroom who can give '
                "you the key. Aside from that we'll stay out of your hair!",
 'jurisdiction_names': 'SAN FRANCISCO',
 'last_review': '2016-04-07',
 'last_scraped': '2017-04-02',
 'latitude': '37.76221382842841',
 'listing_url': 'https://www.airbnb.com/rooms/11067041',
 'longitude': '-122.42032216865074',
 'market': 'San Francisco',
 'maximum_nights': 1125,
 'medium_url': 'https://a0.muscache.com/im/pictures/24d59318-c5d1-439d-b517-843565bd794a.jpg?aki_policy=medium',
 'minimum_nights': 1,
 'name': 'Single Bedroom in Mission 2br Apt',
 'neighborhood_overview': "We're in the heart of the Mission. Located on a "
                          'small, quiet street between Valencia and Mission '
                          'Streets, we are surrounded by all the awesome bars, '
                          'restaurants and shopping of the Mission. Some of my '
                          'favorite things about the Mission: Craft beer bars '
                          'The best tacos/burritos  Dolores Park '
                          'Michelin-starred restaurants Tartine Bakery Hipster '
                          'fashion Artisinal chocolate factories Amazing '
                          'coffee  Incredible murals  Sunshine (The Mission '
                          'gets more sun that the rest of San Francisco) And '
                          'all of this is available within 2 minute walk from '
                          'the house! I have a long detailed list of my '
                          'favorite bars, restaurants, coffee shops, '
                          'attractions and activities in San Francisco that I '
                          "will share with you once you're booked! And don't "
                          "hesitate to ask if there's something in particular "
                          "you're looking for.",
 'neighbourhood': 'Mission District',
 'neighbourhood_cleansed': 'Mission',
 'notes': "We're in the heart of the Mission. Located on a small, quiet street "
          'between Valencia and Mission Streets, we are surrounded by all the '
          'awesome bars, restaurants and shopping of the Mission. Craft beer '
          'bars The Best Tacos and Burritos Dolores Park Michelin-starred '
          'restaurants Tartine Bakery Hipster fashion Artisinal chocolate '
          'factories GREAT coffee  Incredible murals  Sunshine (The Mission '
          'gets more sun that the rest of San Francisco) These are just some '
          'of the things available within a one minute walk from our pad. As '
          'foodies we have a list of amazing bars and restaurants you should '
          "check out while you're here. And don't hesitate to ask if there's "
          "something in particular you're looking for. Getting Around The BART "
          '(aka subway, train, tube, etc.) is located at 16th and Mission. '
          "That's two blocks from the apartment and it will take you anywhere "
          'and everywhere in the city and in the Bay Area - most importantly '
          'it will take you to Super Bowl City in 6 minutes - yes I timed it.  '
          'You can als',
 'number_of_reviews': 2,
 'picture_url': {'filename': '24d59318-c5d1-439d-b517-843565bd794a.jpg',
                 'height': 426,
                 'id': '1e010f2b91e960b3ce742eb8467b3ab5',
                 'mimetype': 'image/jpeg',
                 'width': 639},
 'price': 125,
 'property_type': 'Apartment',
 'review_scores_accuracy': 10,
 'review_scores_checkin': 10,
 'review_scores_cleanliness': 10,
 'review_scores_communication': 10,
 'review_scores_location': 10,
 'review_scores_rating': 100,
 'review_scores_value': 10,
 'reviews_per_month': 0.14,
 'room_type': 'Private room',
 'scrape_id': '20170401232214',
 'smart_location': 'San Francisco, CA',
 'space': 'The two-bedroom, one-bathroom has fast wifi, a large living room '
          '(with a TV with HBO and HBO-on-Demand with every season of every '
          'show!). Our kitchen has a 4-top stove and oven. Large refrigerator '
          'and freezer and full suite of cooking and eating utensils. The '
          'bathroom has a shower with hot water, great water pressure and '
          'soap, shampoo and conditioner + fluffy clean towels. The bedroom is '
          'spacious with a desk, dresser and mirror.',
 'state': 'CA',
 'street': 'Mission District, San Francisco, CA 94110, United States',
 'summary': 'Single bedroom in awesomely-located Mission 2br apartment for '
            'weekend adventures. Just feet from the best restaurants, bars and '
            'shopping of Valencia Street and the Mission District and just two '
            'blocks from the BART train.',
 'thumbnail_url': 'https://a0.muscache.com/im/pictures/24d59318-c5d1-439d-b517-843565bd794a.jpg?aki_policy=small',
 'transit': 'The BART (aka subway, train, tube, etc.) is located at 16th and '
            "Mission. That's two blocks from the apartment and it will take "
            'you anywhere and everywhere in the city and in the Bay Area. You '
            'can also take the BART to and from the airport, the Embarcadero, '
            'Union Square, Oracle Arena, Oakland, Berkeley. There are also '
            'dozens of bus lines running through the Mission. Walking and '
            'biking are really easy from the Mission as there are no hills '
            'between this neighborhood and downtown.',
 'xl_picture_url': 'https://a0.muscache.com/im/pictures/24d59318-c5d1-439d-b517-843565bd794a.jpg?aki_policy=x_large',
 'zipcode': '94110'}

In [ ]:
# results = [r["fields"] for r in result[0]]
#results

In [7]:
results_df = pd.DataFrame(result[0])
results_df.head()

,access,accommodates,amenities,availability_30,availability_365,availability_60,availability_90,bathrooms,bed_type,bedrooms,...,space,square_feet,state,street,summary,thumbnail_url,transit,weekly_price,xl_picture_url,zipcode
0,We're in the heart of the Mission. Located on ...,2.0,"TV,Wireless Internet,Kitchen,Buzzer/wireless i...",0,0,0,0,0.0,Real Bed,1.0,...,"The two-bedroom, one-bathroom has fast wifi, a...",NaN,CA,"Mission District, San Francisco, CA 94110, Uni...",Single bedroom in awesomely-located Mission 2b...,https://a0.muscache.com/im/pictures/24d59318-c...,"The BART (aka subway, train, tube, etc.) is lo...",NaN,https://a0.muscache.com/im/pictures/24d59318-c...,94110
1,NaN,3.0,"TV,Cable TV,Wireless Internet,Kitchen,Elevator...",30,365,60,90,2.0,Real Bed,3.0,...,Airy and open,NaN,CA,"Pacific Heights, San Francisco, CA 94115, Unit...",I paint for fun and have my paintings in my ap...,NaN,NaN,NaN,NaN,94115
2,Guests will have shared access to all the comm...,4.0,"TV,Internet,Wireless Internet,Kitchen,Free par...",13,320,28,52,1.0,Real Bed,1.0,...,I have hosted on Airbnb for about 1 year and i...,NaN,CA,"Visitacion Valley, San Francisco, CA 94134, Un...",- 4 min walk to Caltrain Station - 3 min walk ...,https://a0.muscache.com/im/pictures/103767962/...,- Steps away from the Caltrain Station and Mun...,NaN,https://a0.muscache.com/im/pictures/103767962/...,94134
3,Shared access through the front door. You are...,2.0,"TV,Internet,Wireless Internet,Heating,Family/k...",30,89,60,89,1.5,Real Bed,1.0,...,NOTE: Please send us a note to introduce yours...,NaN,CA,"Presidio Heights, San Francisco, CA 94118, Uni...",Our house is open for easy going & fun loving ...,https://a0.muscache.com/im/pictures/51060948/d...,Some popular places within 10mins walk: Trader...,NaN,https://a0.muscache.com/im/pictures/51060948/d...,94118
4,If possible. we will meet you and give you key...,2.0,"TV,Cable TV,Internet,Wireless Internet,Air con...",1,95,6,13,1.0,Real Bed,1.0,...,The space has everything you need plus the cha...,NaN,DC,"Capitol Hill, Washington, DC 20002, United States",Feel at home in this cozy first-floor apartmen...,https://a0.muscache.com/im/pictures/91ea8410-0...,NaN,NaN,https://a0.muscache.com/im/pictures/91ea8410-0...,20002

In [9]:
columns = results_df.columns.tolist()
columns

['access',
 'accommodates',
 'amenities',
 'availability_30',
 'availability_365',
 'availability_60',
 'availability_90',
 'bathrooms',
 'bed_type',
 'bedrooms',
 'beds',
 'calculated_host_listings_count',
 'calendar_last_scraped',
 'calendar_updated',
 'cancellation_policy',
 'city',
 'cleaning_fee',
 'country',
 'country_code',
 'description',
 'experiences_offered',
 'extra_people',
 'features',
 'first_review',
 'geolocation',
 'guests_included',
 'has_availability',
 'host_about',
 'host_acceptance_rate',
 'host_id',
 'host_listings_count',
 'host_location',
 'host_name',
 'host_neighbourhood',
 'host_picture_url',
 'host_response_rate',
 'host_response_time',
 'host_since',
 'host_thumbnail_url',
 'host_total_listings_count',
 'host_url',
 'host_verifications',
 'house_rules',
 'id',
 'interaction',
 'jurisdiction_names',
 'last_review',
 'last_scraped',
 'latitude',
 'license',
 'listing_url',
 'longitude',
 'market',
 'maximum_nights',
 'medium_url',
 'minimum_nights',
 'monthly_price',
 'name',
 'neighborhood_overview',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'notes',
 'number_of_reviews',
 'picture_url',
 'price',
 'property_type',
 'review_scores_accuracy',
 'review_scores_checkin',
 'review_scores_cleanliness',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_rating',
 'review_scores_value',
 'reviews_per_month',
 'room_type',
 'scrape_id',
 'security_deposit',
 'smart_location',
 'space',
 'square_feet',
 'state',
 'street',
 'summary',
 'thumbnail_url',
 'transit',
 'weekly_price',
 'xl_picture_url',
 'zipcode']

In [10]:
cleanData = results_df[[ 'price','id', 'geolocation', 'room_type', "city", 'country']]
cleanData.head()

,price,id,geolocation,room_type,city,country
0,125.0,11067041,"[37.76221382842841, -122.42032216865074]",Private room,San Francisco,United States
1,NaN,5859735,"[37.79561314356756, -122.43301209465291]",Entire home/apt,San Francisco,United States
2,100.0,8048653,"[37.7129876927169, -122.40016991761325]",Private room,San Francisco,United States
3,129.0,3310076,"[37.78270446257035, -122.45475592448159]",Private room,San Francisco,United States
4,130.0,10923918,"[38.89277378649149, -76.99767929786395]",Entire home/apt,Washington,United States

In [11]:
cleanData = cleanData.rename(index=str, columns={"price":"Price",
                                                 "id":"Room_Id", 
                                                 "geolocation":"Coordinates",
                                                 "country":"Country", 
                                                 "room_type":"Room_Type",
                                                 "city":"City"})

cleanData.head()

,Price,Room_Id,Coordinates,Room_Type,City,Country
0,125.0,11067041,"[37.76221382842841, -122.42032216865074]",Private room,San Francisco,United States
1,NaN,5859735,"[37.79561314356756, -122.43301209465291]",Entire home/apt,San Francisco,United States
2,100.0,8048653,"[37.7129876927169, -122.40016991761325]",Private room,San Francisco,United States
3,129.0,3310076,"[37.78270446257035, -122.45475592448159]",Private room,San Francisco,United States
4,130.0,10923918,"[38.89277378649149, -76.99767929786395]",Entire home/apt,Washington,United States

In [12]:
# Create two lists for the loop results to be placed
lat = []
lon = []

# For each row in a varible,
for row in cleanData['Coordinates']:
   # Try to,
   try:
       # Split the row by comma and append
       # everything before the comma to lat
       lat.append(row[0])
       # Split the row by comma and append
       # everything after the comma to lon
       lon.append(row[1])
   # But if you get an error
   except:
       # append a missing value to lat
       lat.append(np.NaN)
       # append a missing value to lon
       lon.append(np.NaN)

# Create two new columns from lat and lon
cleanData['Room_Lat'] = lat
cleanData['Room_Long'] = lon

In [ ]:
# cleanData = cleanData.drop(columns=["Coordinates"])
# cleanData.head()

In [13]:
cleanData["Selection"] = cleanData["City"]+", "+cleanData["Country"]
cleanData.head(5)

,Price,Room_Id,Coordinates,Room_Type,City,Country,Room_Lat,Room_Long,Selection
0,125.0,11067041,"[37.76221382842841, -122.42032216865074]",Private room,San Francisco,United States,37.762214,-122.420322,"San Francisco, United States"
1,NaN,5859735,"[37.79561314356756, -122.43301209465291]",Entire home/apt,San Francisco,United States,37.795613,-122.433012,"San Francisco, United States"
2,100.0,8048653,"[37.7129876927169, -122.40016991761325]",Private room,San Francisco,United States,37.712988,-122.400170,"San Francisco, United States"
3,129.0,3310076,"[37.78270446257035, -122.45475592448159]",Private room,San Francisco,United States,37.782704,-122.454756,"San Francisco, United States"
4,130.0,10923918,"[38.89277378649149, -76.99767929786395]",Entire home/apt,Washington,United States,38.892774,-76.997679,"Washington, United States"

In [15]:
cleanData['City'] = cleanData['City'].str.replace('-',' ')
# cleanData

In [36]:
cities = []

for index, row in cleanData.iterrows():
    if row["Selection"] not in cities:
        cities.append(row["Selection"])

cities_df = pd.DataFrame(cities)
cities_df

                                                     0
0                         San Francisco, United States
1                            Washington, United States
2             Dupont Circle, Washington, United States
3                            Santa Cruz, United States
4                               Seattle, United States
5                                Soquel, United States
6                           Rio Del Mar, United States
7                              Bethesda, United States
8                           Hyattsville, United States
9                              Brooklyn, United States
10                        Mount Rainier, United States
11                     Washington, D.C., United States
12   Washington, District of Columbia, US, United S...
13                        Silver Spring, United States
14                          Watsonville, United States
15                        Boulder Creek, United States
16                            Los Gatos, United States
17                           Ben Lomond, United States
18                      Capitol Heights, United States
19                                Aptos, United States
20                                  旧金山, United States
21                               Felton, United States
22                           Bonny Doon, United States
23                            Davenport, United States
24                             Capitola, United States
25                         Temple Hills, United States
26                             Berkeley, United States
27            Aptos Hills-Larkin Valley, United States
28                        Scotts Valley, United States
29        Bernal Heights, San Francisco, United States
..                                                 ...
709                    Lake Los Angeles, United States
710      Santa Clarita (Canyon Country), United States
711                       Monterey park, United States
712                                艾尔蒙地, United States
713                                西科维纳, United States
714                      woodland Hills, United States
715                       Belmont Shore, United States
716                      Phillips Ranch, United States
717        Hollywood Hills, Los Angeles, United States
718                       Beverly hills, United States
719                            portland, United States
720                                 Los, United States
721                       Santa Barbara, United States
722                  Brooklyn\nBrooklyn, United States
723                    Astoria New York, United States
724                         Kew gardens, United States
725                  Ozone Park, Queens, United States
726                Venice (Los Angeles), United States
727                             venice,, United States
728                         lake balboa, United States
729               Pasadena, Los Angeles, United States
730                      Marina del rey, United States
731                           Echo Park, United States
732                         Diamond bar, United States
733                         Old Hickory, United States
734        Los Angeles, Hollywood Hills, United States
735        Granada Hills, (Los Angeles), United States
736                         Quartz Hill, United States
737     Los Angeles (Montecito Heights), United States
738                            Van nuys, United States

[739 rows x 1 columns]

In [53]:
city_lats = []
city_lons =[]

for index, row in cities_df.iterrows():
    
#     pprint(row[0])
    
    gkey = "AIzaSyAL_3t-K2F-8_HQde0JpXON-x_X70Nn5Mw"
    target_url = ('https://maps.googleapis.com/maps/api/geocode/json?'
    'address={0}&key={1}').format(row[0], gkey)
    
    try
    
    cities_lat_long = requests.get(target_url).json()
    city_lat = cities_lat_long["results"][0]["geometry"]["location"]["lat"]
    city_long = cities_lat_long["results"][0]["geometry"]["location"]["lng"]
    
    city_lats.append(city_lat)
    city_lons.append(city_long)
    
    except
    city_lats.append("")
    city_lons.append("")

37.7749295
47.7510741
38.9096936
36.9741171
47.6062095
36.9880057
36.9597903
38.984652
38.9559442
40.6781784
38.9415
38.9071923
38.9071923
38.99066570000001
36.910231
37.12605780000001
37.2358078
37.0891143
38.8851122
36.97717290000001
37.7749295
37.0513374
37.0416156
41.5236437
36.9752283
38.8140024
37.8715926
36.9637177
37.0510595
37.7389496
47.5666668
38.9097057
37.7598648
47.6062095
37.7749295
36.988562
47.6062095
37.0494418
36.9597903
33.8622366
34.0522342
34.0928092
34.0928092
34.055103
33.9930677
33.9164032
34.1425078
38.4783198
34.1361187
34.0211224
34.2068182
33.9616801
34.228754
34.1008426
33.887237
33.9761238
33.9816812
33.9802893
33.8536269
33.9172357
40.0378755
34.0200114
34.0152567
33.9850469
33.7700504
37.7749295
34.1477849
33.7444613
33.8491816
34.1466467
42.10808340000001
60.77305560000001
38.67851570000001
34.165357
34.0259216
33.9850469
34.0194543
34.0202894
33.8358492
34.2011141
34.0805651
36.1626638
37.931868
34.1161196
33.791638
34.1395597
33.954737
34.1616729
38.8860434
37.6879241
34.187044
34.0919452
34.1367208
34.1533395
34.3931105
34.0686208
34.1973122
34.0900091
34.0736204
34.3916641
34.4235425
33.9472359
38.9096936
36.9366186
42.3600825
42.3875968
42.33176419999999
42.2797554
30.267153
30.3679788
39.7392358
41.8781136
41.8781136
29.95106579999999
38.9778882
40.8447819
40.7282239
40.592658
40.592658
40.744679
46.1878841
40.7127753
40.7127753
40.7408584
40.7585569
40.7127753
40.5795317
40.744679
40.7127753
33.5386523
40.705695
42.74251659999999
40.7127753
40.744679
40.6710672
40.8382522
40.7156628
40.6733676
40.72557219999999
40.718106
40.72557219999999
40.9792645
43.1558097
37.7749295
33.8752935
40.737975
41.8994744
40.7127753
40.6896834
40.718106
40.67764
40.7674987
40.7127753
37.09024
40.6781784
40.6781784
40.6781784
37.8043637
37.831316
45.5154586
45.5098388
40.7737505
38.9071923
38.9293114
36.9880057
37.7749295
34.0736204
33.8894598
34.03563310000001
34.1066756
34.09611110000001
34.1489719
30.9842977
34.0522342
34.0966764
34.0900091
34.1442616
34.2793576
41.11774399999999
34.190162
34.1397292
34.1397292
34.1336186
33.9564194
34.1808392
34.0286226
33.9401088
34.0686206
33.9191799
34.1517492
33.8883487
33.930293
33.8847361
34.5794343
34.0223519
34.095287
34.4890363
37.7502378
36.8724209
40.833711
47.67478329999999
47.6792172
37.4418834
38.9692771
30.267153
39.613321
42.3736158
42.3782065
42.3600825
42.3539038
30.2979843
41.8781136
39.7392358
42.5294773
42.3381437
42.3097365
42.3151978
34.1394513
34.0522342
33.9608461
33.7922392
33.8674044
33.8816818
34.0625106
34.1397292
39.101225
34.1633045
33.8583483
34.0522342
33.8316745
34.2822134
34.0165053
33.9830688
34.1395597
34.1494848
34.1072305
34.1501794
34.186682
33.8044614
34.165357
34.165357
33.7360619
33.9942689
33.9761238
34.2819461
32.8711596
33.9802893
34.1898566
33.9616801
34.1176605
42.4850931
34.1705609
34.1397292
34.0852868
42.2832142
30.2285878
41.8781136
41.6628909
42.30163049999999
33.8005714
33.8958492
34.0224417
34.09751
33.9850469
34.1395597
30.2751945
34.0900091
34.208254
34.0005691
34.4963817
34.1808392

IndexError: list index out of range

In [43]:
city_lats

[34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091,
 34.0900091]

In [33]:
cities_df['lat'] = city_lats
cities_df['lon'] = city_lons

cities_df.columns = ["Selection", "Center Lat", "Center Lon"]

cleanData = cleanData.merge(cities_df, left_on='Selection', right_on='Selection')

In [38]:
cities_df

                                                     0
0                         San Francisco, United States
1                            Washington, United States
2             Dupont Circle, Washington, United States
3                            Santa Cruz, United States
4                               Seattle, United States
5                                Soquel, United States
6                           Rio Del Mar, United States
7                              Bethesda, United States
8                           Hyattsville, United States
9                              Brooklyn, United States
10                        Mount Rainier, United States
11                     Washington, D.C., United States
12   Washington, District of Columbia, US, United S...
13                        Silver Spring, United States
14                          Watsonville, United States
15                        Boulder Creek, United States
16                            Los Gatos, United States
17                           Ben Lomond, United States
18                      Capitol Heights, United States
19                                Aptos, United States
20                                  旧金山, United States
21                               Felton, United States
22                           Bonny Doon, United States
23                            Davenport, United States
24                             Capitola, United States
25                         Temple Hills, United States
26                             Berkeley, United States
27            Aptos Hills-Larkin Valley, United States
28                        Scotts Valley, United States
29        Bernal Heights, San Francisco, United States
..                                                 ...
709                    Lake Los Angeles, United States
710      Santa Clarita (Canyon Country), United States
711                       Monterey park, United States
712                                艾尔蒙地, United States
713                                西科维纳, United States
714                      woodland Hills, United States
715                       Belmont Shore, United States
716                      Phillips Ranch, United States
717        Hollywood Hills, Los Angeles, United States
718                       Beverly hills, United States
719                            portland, United States
720                                 Los, United States
721                       Santa Barbara, United States
722                  Brooklyn\nBrooklyn, United States
723                    Astoria New York, United States
724                         Kew gardens, United States
725                  Ozone Park, Queens, United States
726                Venice (Los Angeles), United States
727                             venice,, United States
728                         lake balboa, United States
729               Pasadena, Los Angeles, United States
730                      Marina del rey, United States
731                           Echo Park, United States
732                         Diamond bar, United States
733                         Old Hickory, United States
734        Los Angeles, Hollywood Hills, United States
735        Granada Hills, (Los Angeles), United States
736                         Quartz Hill, United States
737     Los Angeles (Montecito Heights), United States
738                            Van nuys, United States

[739 rows x 1 columns]

In [ ]:
calculated_distance = []

for index, row in cleanData.iterrows():
    room_lat1 = row['Room_Lat']
    room_long1 = row['Room_Long']
    city_lat2 = row['Center Lat']
    city_long2 = row['Center Lon']
    
#CALCULATES DISTANCE OF ROOMS AND CITIES LAT AND LONGS
    def distance(room_long1, room_lat1, city_long2, city_lat2):
        room_long1, room_lat1, city_long2, city_lat2 = map(radians, [room_long1, room_lat1, city_long2, city_lat2])
        dlon = city_long2 - room_long1
        dlat = city_lat2 - room_lat1
        a = sin(dlat / 2) ** 2 + cos(room_lat1) * cos(city_lat2) * sin(dlon / 2) ** 2
        return 2 * 3958.756 * asin(sqrt(a)) #6371 km / 3958.756 for miles

    room_city_distance = distance(room_long1, room_lat1, city_long2, city_lat2)

    
    calculated_distance.append(room_city_distance)
    
print("calculated_distance:", calculated_distance)

In [ ]:
cleanData['Calc_Distance'] = calculated_distance

In [ ]:
cleanData.head()

In [ ]:
cleanData= cleanData.drop(columns=["Coordinates","Center Lat", "Center Lon"])
cleanData.head()

In [ ]:
# #Export city names to csv
# cleanData.to_csv('../data.csv', index=False)

# # Import cities file as DataFrame
# cleanData_df = pd.read_csv("../data.csv")
# cleanData_df.head()

In [ ]:
# this site confirmed the calculation is correct:
# https://www.gpsvisualizer.com/calculators

In [ ]:
cleanData = cleanData.rename(index=str, columns={"Room_Lat":"Latitude",
                                                 "Room_Long":"Longitude", 
                                                 "Calc_Distance":"Distance"})

cleanData.head()

In [ ]:
conn_str = "root:helpme01@localhost/airbnb_data"
engine = create_engine(f'mysql://{conn_str}')

if not database_exists(engine.url):
    create_database(engine.url)

In [ ]:
engine.table_names()

In [ ]:
metadata = MetaData(engine)

listings = Table('listings', metadata,
                 Column('Price', Integer),
                 Column('Room_Id', String(10)),
                 Column('Room_Type', String(25)),
                 Column('City', String(50)),
                 Column('Country', String(50)),
                 Column('Latitude', Float),
                 Column('Longitude', Float),
                 Column('Selection', String(100)),
                 Column('Distance', Float))

metadata.create_all()
for _t in metadata.tables:
    print("Table: ",_t)

In [ ]:
cleanData.to_sql(name="listings", con=engine, if_exists="append",index=False)

In [ ]:
# selection = cleanData["Selection"]
selection1 = pd.DataFrame(cleanData.drop_duplicates(["Selection"]))
selection1 = selection1["Selection"]
selection1.head()

In [ ]:
listings_total_count = cleanData.shape[0]

grouped_listings = cleanData.groupby(['Selection'])
grouped_listings.count().head()

listings_count_per_city = grouped_listings['Selection'].value_counts()
# print(listings_count_per_city)

listings_perc_per_city = listings_per_city / listings_total_count*100
# print(listings_perc_per_city)

listings_total_price = grouped_listings['Price'].sum()
#print(listings_total_price)

listings_avg_price = listings_total_price / listings_per_city
# print(listings_avg_price)

selection2 = pd.DataFrame({"Number_of_Listings": listings_per_city, 
                            "Perc_of_Listings": listings_perc_per_city,
                            "Avg_Price": listings_avg_price})

selection2["Perc_of_Listings"] = selection2["Perc_of_Listings"].map("{:.0f}".format)

selection2.reset_index(drop=True, inplace=True)

selection2.head()

In [ ]:
# min_price= cleanData.groupby('Selection')['Price'].transform('min')
# max_price = cleanData.groupby('Selection')['Price'].transform('max')
                                      
# selection3 = pd.DataFrame({"Max_Price": max_price.drop_duplicates(),
#                             "Min_Price": min_price.drop_duplicates()})

# selection_1_3 = pd.concat([selection1, selection3,], axis=1)
# selection_1_3


selection_df = cities_df.merge(selection2,left_index=True, right_index=True)
selection_df

In [ ]:
# selection_df = selection2.merge(pd.DataFrame(data = [selection1.values] * len(selection1), columns = selection1.index), left_index=True, right_index=True)
# selection_df = selection_df.rename(index=str, columns={"0":"Selection"}) 
# selection_df

In [ ]:
cities = Table('cities', metadata,
                 Column('Selection', String(100)),
                 Column('Number_of_Listings', Float),
                 Column('Perc_of_Listings', Float),
                 Column('Avg_Price', Float),
                 Column('Center Lat', Float),
                 Column('Center Lon', Float)

#                  Column('Min_Price', Float),
#                  Column('Max_Price', Float),
              )

metadata.create_all()
for _t in metadata.tables:
    print("Table: ",_t)

In [ ]:
selection_df.to_sql(name="cities", con=engine, if_exists="append",index=False)